// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ighldjfpfcealipljncs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnaGxkamZwZmNlYWxpcGxqbmNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTI4NTQsImV4cCI6MjA2MzcyODg1NH0.xzTwtK7uEIJlF5zkNmTV02PRFKE2EWUzrCWfz2A4tt8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);